# Generated by Django 2.2.3 on 2019-12-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='post_pics/test.png', upload_to='post_pics'),
        ),
    ]
